# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=20)),
                ('addtime', models.CharField(max_length=14)),
                ('status_remove', models.IntegerField()),
                ('imgid', models.CharField(max_length=20)),
                ('iam', models.CharField(default='陕西青年', max_length=20)),
                ('itext', models.CharField(default='', max_length=50)),
                ('iwhere', models.CharField(default='陕西省,,', max_length=50)),
            ],
        ),
    ]
