# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='utext',
        ),
        migrations.AddField(
            model_name='item',
            name='iam',
            field=models.CharField(default='陕西青年', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='itext',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='iwhere',
            field=models.CharField(default='陕西省,,', max_length=50),
        ),
    ]
