# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180115_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imghdw',
            field=models.FloatField(default=1),
        ),
    ]
