# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_igps'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='igpswhere',
            field=models.CharField(default='陕西省,,', max_length=50),
        ),
    ]
