# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_igpswhere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imgid',
            field=models.CharField(max_length=200),
        ),
    ]
